version: 0.2

env:
  variables:
    MODEL: "0.0.1"
    DEFAULT_BUCKET: "bucket-test"
    SAGEMAKER_PROJECT_NAME_ID: "prj-test"
  exported-variables:
    - MODEL
    - CODEBUILD_START_TIME
    - AWS_REGION
    - DEFAULT_BUCKET
    - SAGEMAKER_PROJECT_NAME_ID
    
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade --force-reinstall pip
      - pip install --upgrade --force-reinstall "awscli==1.22.8"
      - pip install --upgrade --force-reinstall "sagemaker==2.80.0"
      - pip install --upgrade --force-reinstall "pandas==1.3.5"
      - pip install --upgrade --force-reinstall "protobuf==3.20.1"
  
  build:
    commands:
      - export PYTHONUNBUFFERED=TRUE
      - export SAGEMAKER_PROJECT_NAME_ID="${SAGEMAKER_PROJECT_NAME_ID}"
      - python3 run_pipeline.py --region "${AWS_REGION}" --default-bucket "${DEFAULT_BUCKET}"
      - echo "Create/Update of the SageMaker Pipeline and execution completed."